[package]
name = "eliza-discord"
version = "0.1.0"
edition = "2021"

[dependencies]
eliza = "2.0.0"
serenity = { version = "0.10.10", default-features = false, features = ["client", "gateway", "model", "rustls_backend"] }
tokio = { version = "1.17", features = ["macros", "rt-multi-thread"] }
